signUp:
  method    : POST
  path      : /signup
  controller: Dolphin\Ting\Http\Controller\User\SignUpController
signIn:
  method    : POST
  path      : /signin
  controller: Dolphin\Ting\Http\Controller\User\SignInController
userInfo:
  method    : GET
  path      : /user
  controller: Dolphin\Ting\Http\Controller\User\UserController
createCategory:
  method    : POST
  path      : /category
  controller: Dolphin\Ting\Http\Controller\Category\CreateController
category:
  method    : GET
  path      : /category/{category_id}
  controller: Dolphin\Ting\Http\Controller\Category\CategoryController
userCategory:
  method    : GET
  path      : /user/category
  controller: Dolphin\Ting\Http\Controller\Category\UserCategoryController
removeCategory:
  method    : GET
  path      : /category/remove/{category_id}
  controller: Dolphin\Ting\Http\Controller\Category\RemoveCategoryController
passwordGenerator:
  method    : POST
  path      : /password/generator
  controller: Dolphin\Ting\Http\Controller\Password\GeneratorController
createApplication:
  method    : POST
  path      : /application
  controller: Dolphin\Ting\Http\Controller\Application\CreateApplicationController
applicationType:
  method    : GET
  path      : /application/type
  controller: Dolphin\Ting\Http\Controller\Application\ApplicationTypeController
application:
  method    : GET
  path      : /application/{application_id}
  controller: Dolphin\Ting\Http\Controller\Application\ApplicationController
categoryApplication:
  method    : GET
  path      : /category/application/{category_id}
  controller: Dolphin\Ting\Http\Controller\Application\CategoryApplicationController
config:
  method    : GET
  path      : /config
  controller: Dolphin\Ting\Http\Controller\Config\ConfigController
userConfirm:
  method    : GET
  path      : /confirm
  controller: Dolphin\Ting\Http\Controller\User\ConfirmController
